dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - go test -v -coverpkg=./tests -coverprofile=coverage.txt -covermode=atomic ./tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
